# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66bbe53ff571c84b176be3e3e127871e78d537bcc3f4b04db8a844adbbf70ac3560d2a5fc3af72dff6f9918aeda6060d3428f96b41418f08d2cce2d47b1bfc85

test:
  secret_key_base: 53d1a8dea483403190a1a19e2018be0af146199284e0206ebea2759e7ba892f522f4eb6d1c9d9bd2649fa3fa7ff4759f8ff072e124fd523de9b9aecfbbca27b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
